FROM node:20-alpine

RUN addgroup prod && adduser -S -G prod prod

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN chown -R prod:prod /app

USER prod

EXPOSE 3000

CMD ["npm", "start", "--", "--host"]
