FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ENV DATABASE_PUBLIC_URL=postgresql://postgres:fyCseTFDwmxmBZWEyHcauPxsledzDGhH@junction.proxy.rlwy.net:13881/railway

EXPOSE 8080

RUN go build -o expense-tracker ./cmd/expense-tracker/main.go

CMD ["./expense-tracker"]